version: 1
events:
events:
  temperature:
    url: http://storage/storage/temperature/condition
  traffic:
    url: http://storage/storage/traffic/condition
  hostname: kafka
  port: 9092
  topic: events