version: 1
datastore:
  filename: /app/data/data.json
scheduler:
  interval: 5
eventstores:
  temperature:
    url: http://dashboard/storage/temperature/condition
  traffic:
    url: http://dashbboard/storage/traffic/condition
